name: Android CI

on: [ push, pull_request ]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Setup Gradle
        run: chmod +x gradlew
      - name: Gradle build
        run: bash ./gradlew build
      - name: Unit tests
        run: bash ./gradlew test --stacktrace
      - name: kltlint check
        run: bash ./gradlew ktlintCheck