name: Gradle Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
                
    - name: cd to app dir
      run: cd /home/runner/work/MediaHub/MediaHub/app
      
    - name: Create Google services json 
      run: |
           'echo "$GOOGLE_SERVICES" > google-services.json'
           'ls'
           'cd ..'  
      shell: bash
      env:
        GOOGLE_SERVICES: ${{secrets.GOOGLE_SERVICES}}
          
    - name: Setup Gradle
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build
