name: Gradle Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
                
    - name: Create Google services json 
      run: |
           'cd /home/runner/work/MediaHub/MediaHub/app'
           'echo "$GOOGLE_SERVICES" > key'
           'ls'
           'cd ..'  
      shell: bash
      env:
        GOOGLE_SERVICES: ${{secrets.GOOGLE_SERVICES}}
          
    - name: Setup Gradle
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build
