name: Gradle Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
                
    - name: Create Google services json 
      run: echo $GOOGLE_SERVICES > google-services.json
      env:
        GOOGLE_SERVICES: ${{secrets.GOOGLE_SERVICES}}
       
    - name: move file
      run: mv /home/runner/work/MediaHub/MediaHub/google-services.json /home/runner/work/MediaHub/MediaHub/app
      
    - name: Setup Gradle
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build
