name: Gradle Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
          
    - name: cd to app dir
      run: cd app
      
    - name: Create Google services json
      uses: finnp/create-file-action@1.0.0
      env:
        FILE_NAME: "google-services.json"
        FILE_DATA: ${{ secrets.GOOGLE_SERVICES }}
       
    - name: ls
      run:  ls 
    
    - name: cd to parent folder
      run: cd ..
      
    - name: Setup Gradle
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build
